USE BANCO
GO
IF OBJECT_ID (N'dbo.HSUCURSAL', N'U') IS NOT NULL
DROP TABLE dbo.HSUCURSAL
GO
CREATE TABLE HSUCURSAL(
HSUCURSAL VARCHAR(30),
HCIUDAD VARCHAR(30),
HACTIVOSA DECIMAL(10,3),
HACTIVOSN DECIMAL(10,3),
HFX DATE
)
GO
IF OBJECT_ID ('tr_movSucursal', 'TR') IS NOT NULL
   DROP TRIGGER tr_movSucursal;
GO
CREATE TRIGGER tr_movSucursal ON SUCURSAL AFTER UPDATE
AS 
BEGIN
DECLARE @VALORNUEVO DECIMAL(10,3)

	SET NOCOUNT ON;
	IF UPDATE(ACTIVOS)
	BEGIN
	SET @VALORNUEVO = (SELECT ACTIVOS FROM DELETED)
	INSERT INTO HSUCURSAL(HSUCURSAL,HCIUDAD,HACTIVOSA,HACTIVOSN,HFX)
	SELECT NOMBRESUCURSAL,CIUDADSUCURSAL,@VALORNUEVO,ACTIVOS,GETDATE() FROM INSERTED
	END
END
GO

UPDATE SUCURSAL
SET ACTIVOS = ACTIVOS * 2 WHERE NOMBRESUCURSAL='Becerril'
GO


-- Desactiva el trigger tr_movSucursal

DISABLE TRIGGER tr_movSucursal ON SUCURSAL

GO

-- activa el trigger tr_movSucursal

ENABLE TRIGGER tr_movSucursal ON SUCURSAL

GO

-- Desactiva todos los trigger de la tabla SUCURSAL

ALTER TABLE SUCURSAL DISABLE TRIGGER ALL

GO

-- Activa todos los trigger de la tabla CUENTAS

ALTER TABLE CUENTAS ENABLE TRIGGER ALL 